version: "3"
services:
  zookeeper:
    image: zookeeper

  kafka:
    image: eitanya/kafka:0.11.0.2
    ports:
      - 9092
    environment:
      KAFKA_LOG_CLEANUP_POLICY: "compact"
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 20000
      KAFKA_LOG_SEGMENT_BYTES: 512000
      KAFKA_NUM_PARTITIONS: 16
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 16000      
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 16000
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 10000

  central_station-consumer:
    build:
      context: ./
      dockerfile: Dockerfile.consumer
    image: central_station-consumer:1.0
    environment:
      group.id: cool-consumer
      bootstrap.servers: kafka:9092
      TOPIC: mytopic
      
      
  central_station-producer:
    build:
      context: ./
      dockerfile: Dockerfile.producer
    image: central_station-producer:1.0
    environment:
      bootstrap.servers: kafka:9092
      TOPIC: mytopic